# Generated by Django 4.1 on 2022-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='as_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
