# Generated by Django 4.1 on 2022-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_signup_as_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
