# Generated by Django 4.1 on 2022-12-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_signup_username_alter_signup_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user_name',
        ),
    ]
