# Generated by Django 4.1 on 2022-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_username_signup_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='username',
        ),
    ]
