# Generated by Django 4.1 on 2022-12-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_user_name_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
