# Generated by Django 4.1.5 on 2023-01-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_signup_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
