# Generated by Django 4.2.1 on 2023-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('sorted', 'Sorted'), ('unsorted', 'Unsorted')], default='unsorted', max_length=30),
        ),
    ]
