# Generated by Django 4.2.1 on 2023-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_order_status_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sorted', 'sorted'), ('unsorted', 'unsorted')], default='unsorted', max_length=30),
        ),
    ]
